using System;

namespace SocialMedia.Core.DTOs
{
    public class PostDTO
    {
        /// <summary>
        /// Autogenerated Id for Post Entity
        /// </summary>
        public int PostId { get; set; }
        public int UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
