using SocialMedia.Core.Enumerations;
using System;

namespace SocialMedia.Core.DTOs
{
    public class SecurityDTO
    {
        /// <summary>
        /// Autogenerated Id for Security Entity
        /// </summary>
        public string SecurityId { get; set; }
        public string User { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public RoleType? Role { get; set; }
    }
}
